from django import forms

class SurveyForm(forms.Form):
    DateOrdered = forms.DateField(required=False, input_formats=['%d/%m/%Y'])
    DueDate = forms.DateField(required=False, input_formats=['%d/%m/%Y'])
    Number = forms.CharField(max_length=6, required=True)
    Description = forms.CharField(max_length=99, required=False)
    Amount = forms.IntegerField(required=False)
    NTEPrice = forms.IntegerField(required=False)
    Client = forms.CharField(max_length=50, required=True)
    PhoneNumber = forms.CharField(max_length=12, required=False)
    Address = forms.CharField(max_length=40, required=True)
    City = forms.CharField(max_length=20, required=True)
    State = forms.CharField(max_length=15, required=True)
    County = forms.CharField(max_length=15, required=False)
    FractionalLot = forms.CharField(max_length=30, required=False)
    Section = forms.CharField(max_length=30,required=False)
    Township = forms.CharField(max_length=30, required=False)
    Range = forms.CharField(max_length=30, required=False)
    Subdivision = forms.CharField(max_length=30, required=False)
    BlockSection = forms.CharField(max_length=30, required=False)
    Lot = forms.CharField(max_length=30, required=False)
    Status = forms.CharField(max_length=15, required=True)
    Comments = forms.CharField(max_length=100, required=False)
    Favorite = forms.BooleanField(required=False)
    Hourly = forms.BooleanField(required=False)
    HourlyAmount = forms.CharField(max_length=20, required=False)
